// Command colorpicker lets the user pick the hostname segment color with
// chicle and prints the chosen 256-color index and its hex value to stdout
// for ./build, space separated: "24 #005f87".
package main

import (
	"fmt"
	"os"
	"strconv"
	"strings"

	"github.com/grillermo/chicle"
)

// palette mirrors hostnameColor() in powerline-zsh.go; keep them in sync.
var palette = []int{
	17, 18, 19, 21,
	22, 23, 24, 28,
	52, 88, 124,
	53, 55, 56, 90, 91,
	58, 94, 130,
	161,
}

// ansi16 is the hex of the 16 fixed colors that open the xterm-256 palette;
// everything above them is generated by formula in hexFor.
var ansi16 = []string{
	"#000000", "#800000", "#008000", "#808000",
	"#000080", "#800080", "#008080", "#c0c0c0",
	"#808080", "#ff0000", "#00ff00", "#ffff00",
	"#0000ff", "#ff00ff", "#00ffff", "#ffffff",
}

// hexFor renders a 256-color index as #rrggbb.
func hexFor(c int) string {
	switch {
	case c < 16:
		return ansi16[c]
	case c < 232:
		// 6x6x6 color cube with non-linear channel levels.
		levels := []int{0, 95, 135, 175, 215, 255}
		n := c - 16
		return fmt.Sprintf("#%02x%02x%02x", levels[n/36], levels[n/6%6], levels[n%6])
	default:
		// 24-step grayscale ramp.
		g := 8 + (c-232)*10
		return fmt.Sprintf("#%02x%02x%02x", g, g, g)
	}
}

func main() {
	host, _ := os.Hostname()
	if idx := strings.Index(host, "."); idx != -1 {
		host = host[:idx]
	}

	rows := make([]chicle.Row, len(palette))
	for i, c := range palette {
		n := strconv.Itoa(c)
		// The swatch carries raw ANSI, so it must stay in the last column:
		// chicle pads fixed-width columns by byte count.
		swatch := fmt.Sprintf("\x1b[38;5;15;48;5;%dm %s \x1b[0m", c, host)
		rows[i] = chicle.Row{Key: n, Cols: []string{n, swatch}}
	}

	color, err := chicle.Run(chicle.Config{
		Title:   "Hostname color for powerline-zsh",
		Columns: []chicle.Column{{Title: "Color", Width: 5}, {Title: "Preview"}},
		Rows:    rows,
	})
	if err != nil {
		fmt.Fprintln(os.Stderr, "colorpicker:", err)
		os.Exit(1)
	}
	idx, err := strconv.Atoi(color)
	if err != nil {
		fmt.Fprintln(os.Stderr, "colorpicker: unexpected selection:", color)
		os.Exit(1)
	}
	fmt.Println(idx, hexFor(idx))
}
